### ISSUE TITLE
Version macros not dependent on git

### ISSUE THREAD

**Issue by bapt** [paulfariello/kickpass#3]
Would be nice to not depend on git to set the version macros. Most package system prefers to base their source packages on regular distfiles on which they can have hashes. If I download the distfile from the release tab on github I end up with something non buildable :(

**Comment by paulfariello** [comment]
Thanks for reporting the issue. I've just pushed hotfix/0.1.1 if you want to try it.

**Comment by bapt** [comment]
It works thank you very much expect a FreeBSD package soon :)
